# -*- coding: utf-8 -*-
"""dz4.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BJFmIa_43p5rCE4wbtoSdxaxnASmEoNT
"""

import torch
import triton
import triton.language as tl

@triton.autotune(
    configs=[
        triton.Config({'BLOCK_SIZE': 128},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 256},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 512},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 1024}, num_warps=4),
        triton.Config({'BLOCK_SIZE': 1024}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 2048}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 4096}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 4096}, num_warps=16),
    ],
    key=['N'],
)
@triton.jit
def _layernorm_fwd_kernel(
    X_ptr, Y_ptr, W_ptr, B_ptr,
    Mean_ptr, Rstd_ptr,
    stride_x_row, stride_y_row,
    N, eps,
    BLOCK_SIZE: tl.constexpr,
):
    row = tl.program_id(0)
    X_ptr += row * stride_x_row
    Y_ptr += row * stride_y_row

    mean = 0.0
    _sum = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        x = tl.load(X_ptr + cols, mask=cols < N, other=0.0).to(tl.float32)
        _sum += x
    mean = tl.sum(_sum, axis=0) / N

    _var = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        x = tl.load(X_ptr + cols, mask=cols < N, other=0.0).to(tl.float32)
        x = tl.where(cols < N, x - mean, 0.0)
        _var += x * x
    var = tl.sum(_var, axis=0) / N
    rstd = 1.0 / tl.sqrt(var + eps)

    tl.store(Mean_ptr + row, mean)
    tl.store(Rstd_ptr + row, rstd)

    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        mask = cols < N
        x = tl.load(X_ptr + cols, mask=mask, other=0.0).to(tl.float32)
        w = tl.load(W_ptr + cols, mask=mask, other=0.0).to(tl.float32)
        b = tl.load(B_ptr + cols, mask=mask, other=0.0).to(tl.float32)
        x_hat = (x - mean) * rstd
        y = x_hat * w + b
        tl.store(Y_ptr + cols, y, mask=mask)

@triton.autotune(
    configs=[
        triton.Config({'BLOCK_SIZE': 128},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 256},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 512},  num_warps=4),
        triton.Config({'BLOCK_SIZE': 1024}, num_warps=4),
        triton.Config({'BLOCK_SIZE': 1024}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 2048}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 4096}, num_warps=8),
        triton.Config({'BLOCK_SIZE': 4096}, num_warps=16),
    ],
    key=['N'],
)
@triton.jit
def _layernorm_bwd_kernel(
    X_ptr, DY_ptr, DX_ptr,
    W_ptr, Mean_ptr, Rstd_ptr,
    DW_ptr, DB_ptr,
    stride_x_row, stride_dy_row, stride_dx_row,
    N,
    BLOCK_SIZE: tl.constexpr,
):
    row = tl.program_id(0)
    X_ptr  += row * stride_x_row
    DY_ptr += row * stride_dy_row
    DX_ptr += row * stride_dx_row

    mean = tl.load(Mean_ptr + row)
    rstd = tl.load(Rstd_ptr + row)

    sum_dxhat       = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    sum_dxhat_xhat  = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        mask = cols < N
        x  = tl.load(X_ptr  + cols, mask=mask, other=0.0).to(tl.float32)
        dy = tl.load(DY_ptr + cols, mask=mask, other=0.0).to(tl.float32)
        w  = tl.load(W_ptr  + cols, mask=mask, other=0.0).to(tl.float32)
        x_hat  = (x - mean) * rstd
        dx_hat = dy * w
        x_hat  = tl.where(mask, x_hat,  0.0)
        dx_hat = tl.where(mask, dx_hat, 0.0)
        sum_dxhat      += dx_hat
        sum_dxhat_xhat += dx_hat * x_hat

    c1 = tl.sum(sum_dxhat,      axis=0)
    c2 = tl.sum(sum_dxhat_xhat, axis=0)

    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        mask = cols < N
        x  = tl.load(X_ptr  + cols, mask=mask, other=0.0).to(tl.float32)
        dy = tl.load(DY_ptr + cols, mask=mask, other=0.0).to(tl.float32)
        w  = tl.load(W_ptr  + cols, mask=mask, other=0.0).to(tl.float32)

        x_hat  = (x - mean) * rstd
        dx_hat = dy * w

        dx = (dx_hat - (c1 + x_hat * c2) / N) * rstd
        tl.store(DX_ptr + cols, dx, mask=mask)

        tl.atomic_add(DW_ptr + cols, dy * x_hat, mask=mask)
        tl.atomic_add(DB_ptr + cols, dy,         mask=mask)


class LayerNormTriton(torch.autograd.Function):

    @staticmethod
    def forward(ctx, x, weight, bias, eps=1e-5):
        x_shape = x.shape
        N = x_shape[-1]
        x2d = x.reshape(-1, N).contiguous()
        M = x2d.shape[0]

        y = torch.empty_like(x2d)
        mean = torch.empty(M, device=x.device, dtype=torch.float32)
        rstd = torch.empty(M, device=x.device, dtype=torch.float32)

        _layernorm_fwd_kernel[(M,)](
            x2d, y, weight, bias,
            mean, rstd,
            x2d.stride(0), y.stride(0),
            N, eps,
        )

        ctx.save_for_backward(x2d, weight, bias, mean, rstd)
        ctx.x_shape = x_shape
        return y.reshape(x_shape)

    @staticmethod
    def backward(ctx, dy):
        x2d, weight, bias, mean, rstd = ctx.saved_tensors
        x_shape = ctx.x_shape
        N = x_shape[-1]
        dy2d = dy.reshape(-1, N).contiguous()
        M = dy2d.shape[0]

        dx = torch.empty_like(x2d)
        dW = torch.zeros(N, device=x2d.device, dtype=torch.float32)
        dB = torch.zeros(N, device=x2d.device, dtype=torch.float32)

        _layernorm_bwd_kernel[(M,)](
            x2d, dy2d, dx,
            weight, mean, rstd,
            dW, dB,
            x2d.stride(0), dy2d.stride(0), dx.stride(0),
            N,
        )

        return (
            dx.reshape(x_shape),
            dW.to(weight.dtype),
            dB.to(bias.dtype),
            None,
        )


def layernorm_triton(x, weight, bias, eps=1e-5):
    return LayerNormTriton.apply(x, weight, bias, eps)

def test_correctness():
    torch.manual_seed(0)
    for shape in [(8, 256), (32, 1024), (4, 8, 4096), (16, 2048)]:
        N = shape[-1]
        x = torch.randn(*shape, device='cuda', dtype=torch.float32, requires_grad=True)
        w = torch.randn(N, device='cuda', dtype=torch.float32, requires_grad=True)
        b = torch.randn(N, device='cuda', dtype=torch.float32, requires_grad=True)

        x_ref = x.detach().clone().requires_grad_(True)
        w_ref = w.detach().clone().requires_grad_(True)
        b_ref = b.detach().clone().requires_grad_(True)

        y_tri = layernorm_triton(x, w, b, 1e-5)
        y_ref = torch.nn.functional.layer_norm(x_ref, (N,), w_ref, b_ref, 1e-5)
        torch.testing.assert_close(y_tri, y_ref, atol=1e-4, rtol=1e-4)

        g = torch.randn_like(y_ref)
        y_tri.backward(g)
        y_ref.backward(g)

        torch.testing.assert_close(x.grad, x_ref.grad, atol=1e-3, rtol=1e-3)
        torch.testing.assert_close(w.grad, w_ref.grad, atol=1e-2, rtol=1e-3)
        torch.testing.assert_close(b.grad, b_ref.grad, atol=1e-2, rtol=1e-3)

        print(f"OK shape={shape}")


@triton.testing.perf_report(
    triton.testing.Benchmark(
        x_names=['N'],
        x_vals=[512, 1024, 2048, 4096, 8192, 16384],
        line_arg='provider',
        line_vals=['torch', 'triton'],
        line_names=['PyTorch', 'Triton'],
        styles=[('blue', '-'), ('red', '-')],
        ylabel='GB/s',
        plot_name='layernorm-fwd-bwd',
        args={'M': 4096, 'dtype': torch.float32, 'mode': 'fwd_bwd'},
    )
)
def benchmark(M, N, provider, dtype, mode):
    x = torch.randn(M, N, device='cuda', dtype=dtype, requires_grad=True)
    w = torch.randn(N,    device='cuda', dtype=dtype, requires_grad=True)
    b = torch.randn(N,    device='cuda', dtype=dtype, requires_grad=True)
    dy = torch.randn(M, N, device='cuda', dtype=dtype)

    if provider == 'torch':
        fn = lambda: torch.nn.functional.layer_norm(x, (N,), w, b, 1e-5)
    else:
        fn = lambda: layernorm_triton(x, w, b, 1e-5)

    if mode == 'fwd':
        ms = triton.testing.do_bench(fn)
    else:
        def run():
            y = fn()
            y.backward(dy, retain_graph=True)
        ms = triton.testing.do_bench(run)

    gb = 5 * M * N * x.element_size() * 1e-9
    return gb / (ms * 1e-3)


if __name__ == '__main__':
    test_correctness()
    benchmark.run(print_data=True, show_plots=False)